import type { WorldConfig } from "../types/domain";

export const WORLD_CONFIG: WorldConfig = {
  id: "chainatlas-mvp",
  label: "ChainAtlas",
  defaultRoomId: "ethereum:main",
  spawnPosition: { x: -58, y: 1.25, z: 0 },
  availableRooms: ["ethereum:main", "base:main"],
  interactionZones: [
    {
      id: "swap-building-ethereum",
      label: "Swap Hall",
      kind: "swap",
      roomId: "ethereum:main",
      chain: "ethereum",
      position: { x: -52, y: 0, z: -10 },
      size: { x: 14, y: 6, z: 14 },
      description: "Direct Uniswap interactions for supported pairs.",
    },
    {
      id: "swap-building-base",
      label: "Swap Hall",
      kind: "swap",
      roomId: "base:main",
      chain: "base",
      position: { x: 52, y: 0, z: 20 },
      size: { x: 14, y: 6, z: 14 },
      description: "Direct Uniswap interactions for supported pairs.",
    },
    {
      id: "bridge-gate-eth",
      label: "Bridge",
      kind: "bridge",
      roomId: "ethereum:main",
      position: { x: -10, y: 0, z: 12 },
      size: { x: 18, y: 5, z: 10 },
      description: "Bridge prompt on the Ethereum side.",
    },
    {
      id: "bridge-gate-base",
      label: "Bridge",
      kind: "bridge",
      roomId: "base:main",
      position: { x: 10, y: 0, z: 12 },
      size: { x: 18, y: 5, z: 10 },
      description: "Bridge prompt on the Base side.",
    },
    {
      id: "send-ethereum",
      label: "Courier Post",
      kind: "send",
      roomId: "ethereum:main",
      position: { x: -66, y: 0, z: 12 },
      size: { x: 12, y: 5, z: 12 },
      description: "Direct transfers on Ethereum island.",
    },
    {
      id: "send-base",
      label: "Courier Post",
      kind: "send",
      roomId: "base:main",
      position: { x: 66, y: 0, z: 12 },
      size: { x: 12, y: 5, z: 12 },
      description: "Direct transfers on Base island.",
    },
  ],
};
